name: Hello world worflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on:
      - self-hosted
      - khanh_label
    steps:
      - uses: actions/checkout@v2
